"""add_is_active_index

Revision ID: 96b5d1f5670d
Revises: 5240ad1a1930
Create Date: 2025-07-10 21:24:13.012494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b5d1f5670d'
down_revision: Union[str, Sequence[str], None] = '5240ad1a1930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_variants_is_active'), 'product_variants', ['is_active'], unique=False)
    op.drop_constraint('products_slug_key', 'products', type_='unique')
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.drop_constraint('regions_slug_key', 'regions', type_='unique')
    op.create_index(op.f('ix_regions_slug'), 'regions', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regions_slug'), table_name='regions')
    op.create_unique_constraint('regions_slug_key', 'regions', ['slug'])
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.create_unique_constraint('products_slug_key', 'products', ['slug'])
    op.drop_index(op.f('ix_product_variants_is_active'), table_name='product_variants')
    # ### end Alembic commands ###
