"""add_seo_fields_to_variants_and_remove_from_products

Revision ID: d2a4a651fed2
Revises: f350401611a8
Create Date: 2025-07-10 21:03:02.339656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a4a651fed2'
down_revision: Union[str, Sequence[str], None] = 'f350401611a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('product_variants', sa.Column('seo_text', sa.Text(), nullable=True))
    op.drop_column('products', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('product_variants', 'seo_text')
    op.drop_column('product_variants', 'title')
    # ### end Alembic commands ###
